app_actividad/urls.py
from django.conf.urls import patterns, url
from app_actividad import views

urlpatterns = patterns('',
	url(r'^crear_actividad/',views.crear_actividad, name='crear_actividad'),
        url(r'^crear_subactividad/',views.crear_subactividad, name='crear_subactividad'), # CREAR SUBACTIVIDAD
        url(r'^crear_actividad/',views.crear_actividad, name='crear_actividad'),
        url(r'^visualizar_subactividad/',views.visualizar_subactividad, name='visualizar_subactividad'),
        url(r'^listar_actividad/',views.listar_actividad, name='listar_actividad'),
        url(r'^modificar_actividad/',views.modificar_actividad, name='modificar_actividad'),
        url(r'^eliminar_actividad/',views.eliminar_actividad, name='eliminar_actividad'),
        url(r'^visualizar_actividad/',views.visualizar_actividad, name='visualizar_actividad'),
        url(r'^modificar_form/',views.generar_form_modificar, name='modificar_form'),
        url(r'^cambiar_estado_actividad/',views.cambiar_estado_actividad, name='cambiar_estado_actividad'),	
        url(r'^form_crear/',views.form_crear, name='form_crear'),
        url(r'^asignar_actividad/',views.asignar_actividad, name='asignar_actividad'),
        url(r'^invitar_usuario/',views.invitar_usuario, name='invitar_usuario')
)

app_log/urls.py
from django.conf.urls import patterns, url

from app_log import views as views_log
from django.contrib.auth import views as views_admin

urlpatterns = patterns('',
    url(r'^consultar_log/', views_log.visualizar_accion_user, name='visualizar_log_user'),
)

app_pizarras/urls.py
from django.conf.urls import patterns, url
from rest_framework.urlpatterns import format_suffix_patterns

from app_pizarras import views
from app_pizarras import rest_views

urlpatterns = patterns('',
        url(r'^crear_pizarra/',views.crear_pizarra, name='crear_pizarra'),
        url(r'^listar_pizarra/',views.listar_pizarra, name='listar_pizarra'),
        url(r'^modificar_pizarra/',views.modificar_pizarra, name='modificar_pizarra'),
        url(r'^modificar_form/',views.generar_form_modificar, name='modificar_form'),
        url(r'^eliminar_pizarra/',views.eliminar_pizarra, name='eliminar_pizarra'),
        url(r'^visualizar_pizarra/',views.visualizar_pizarra, name='visualizar_pizarra'),
        url(r'^orden_cronologico/',views.vista_orden_cronologico, name='orden_cronologico'),
        url(r'^orden_estados/',views.vista_orden_estados, name='orden_estados'),
        url(r'^orden_avance/',views.vista_orden_avance, name='orden_avance'),
        url(r'^listar_pizarras_rest/$', rest_views.PizarraList.as_view(), name='listar_pizarra_rest'),
        url(r'^rest_pizarras_usuario/(?P<username>[\w]+)/$', rest_views.PizarraList.as_view(), name='pizarras_usuarios_rest'),
        url(r'^rest/(?P<pk>[0-9]+)/$', rest_views.PizarraDetail.as_view(), name='rest_pizarra_detail'),
)

urlpatterns = format_suffix_patterns(urlpatterns)

app_usuarios/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth import views as views_admin

from rest_framework.urlpatterns import format_suffix_patterns

from app_usuarios import views as views_usuarios
from app_usuarios import rest_views as rest_views_usuarios

urlpatterns = patterns('',
    url(r'^crear_usuario/', views_usuarios.crear_usuario, name='crear_usuario'),
    url(r'^registrar_visitante/', views_usuarios.registrar_visitante, name='registrar_visitante'),
    url(r'^cambiar_contrasena/', views_usuarios.cambiar_contrasena, name='cambiar_contrasena'),
    url(r'^listar_usuarios/', views_usuarios.listar_usuarios, name='listar_usuarios'),
    url(r'^modificar_usuario/', views_usuarios.modificar_usuario, name='modificar_usuario'),
    url(r'^modificar_form/', views_usuarios.modificar_form, name='modificar_form'),
    url(r'^eliminar_usuario/', views_usuarios.eliminar_usuario, name='eliminar_usuario'),
    url(r'^resetpassword/passwordsent/$', views_admin.password_reset_done),
    url(r'^resetpassword/$', views_admin.password_reset, name = "password_reset"),
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', views_admin.password_reset_confirm),
    url(r'^reset/done/$', views_admin.password_reset_complete),
    url(r'^cerrar_sesion/', views_usuarios.logout_view, name='logout_view'),
    url(r'^perfil_usuario/',views_usuarios.perfil_usuario, name='perfil_usuario'),
    url(r'^login/(?P<nombre_usuario>\w+)/(?P<clave>[\w\d]+)/$', rest_views_usuarios.Login.as_view(), name='rest_login'),
    url(r'^crear_usuario_rest/', rest_views_usuarios.UserProfileList.as_view(), name='rest_create_user'),
    #url(r'^login/(?P<nombre_usuario>\w+)/(?P<clave>[\w\d]+)/$', rest_views_usuarios.Login.as_view(), name='rest_login'),
)

urlpatterns = format_suffix_patterns(urlpatterns)

proyecto_pizarras/urls.py
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from dajaxice.core import dajaxice_autodiscover, dajaxice_config

from app_actividad.models import Actividad
from app_usuarios import views as views_usuarios
from app_usuarios.models import UserProfile
from app_usuarios.models import UserProfile
from app_pizarras.models import Pizarra
from app_log.models import Accion
from app_comentarios.models import Comentario

#admin.site.register(UserProfile)
admin.site.register(Pizarra)
admin.site.register(Actividad)
admin.site.register(Comentario)
admin.site.register(Accion)
admin.autodiscover()
dajaxice_autodiscover()

urlpatterns = patterns('',
    url(r'^admin/',                                            include (admin.site.urls)),
    url(r'^account/',                                          include ('django.contrib.auth.urls')),
    url(r'^$', views_usuarios.login_if, name='login_usuario'),
    url(r'^usuarios/',                                         include ('app_usuarios.urls', namespace="app_usuarios")),
    url(r'^pizarras/',                                         include ('app_pizarras.urls', namespace="app_pizarras")),
    url(r'^actividad/',                                        include ('app_actividad.urls', namespace="app_actividad")),
    url(r'^comentarios/',                                      include ('app_comentarios.urls', namespace="app_comentarios")),
    url(dajaxice_config.dajaxice_url,                          include ('dajaxice.urls')),
    url(r'^log/',                                              include ('app_log.urls', namespace="app_log")),
)

urlpatterns += staticfiles_urlpatterns()

app_pizarras/models.py
#coding=utf-8

import re
import datetime

from django.db import models
from django.db.models import Max
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from datetime import date

from app_log.models import ManejadorAccion, Accion

class Pizarra(models.Model):
    """
    Clase pizarra, representa a la tabla de pizarra en la base de datos
    In: models.Model
    Out: --
    Autor: Oriana Gomez y Carla Urrea
    Fecha: 27-10-12 Version 1.0
    """
    idpiz = models.AutoField(primary_key = True)
    nombrepiz = models.CharField(max_length=50)
    descripcionpiz = models.CharField(max_length=150) 
    fechacreacion = models.DateField(auto_now=False, auto_now_add=False)
    fechafinal = models.DateField(auto_now=False, auto_now_add=False)
    avancepiz = models.IntegerField()
    logindueno = models.ForeignKey(User, related_name='pizarra_dueno')
    is_active = models.BooleanField(default = True)

    def __unicode__(self):
        """docstring for __unicode__"""
        return self.nombrepiz #+ ":" + self.fechacreacion + ":" + self.fechafinal

class PersonalizarPizarra(models.Model):
    """
    Metodo que permite guardar las posiciones de las pizarras dentro de la pared de un usuario
    In: models.Model
    Out: --
    Autor: Oriana Gomez y Carla Urrea
    Fecha: 27-10-12 Version 1.0
    """
    login = models.ForeignKey(User, related_name='dueno_personalizar_pizarra')
    pizarra = models.ForeignKey(Pizarra, related_name='pizarra_personalizar_pizarra')
    posicion = models.IntegerField()

def CreadorPizarra(nombrepiz, descripcionpiz, fechacreacion, fechafinal, usuario):
    """
    Metodo que guarda una pizarra en la base de datos generando la id como el siguiente al mas alto
    In: nombrepiz, descripcionpiz, fechacreacion, fechafinal, usuario
    Out: --
    Autor: Juan Arocha
    Fecha: 27-10-12 Version 1.0
    """
    from app_actividad.models import crearActividad

    #   Se crea una instancia que represente a la pizarra nueva   
    nuevo = Pizarra(
        nombrepiz=nombrepiz, 
        descripcionpiz=descripcionpiz,
        fechacreacion=fechacreacion,
        fechafinal=fechafinal,
        avancepiz=0,
        logindueno =  usuario)

    if nuevo.fechacreacion < date.today():
        raise ValidationError(u'\"%s\" Error. La fecha de creacion debe ser mayor o igual a la fecha de hoy' % nuevo.fechacreacion)
    elif nuevo.fechafinal < nuevo.fechacreacion:
        raise ValidationError(u'\"%s\", \"%s\" Error. La fecha final debe ser mayor o igual a la fecha de creacion' % (nuevo.fechacreacion, nuevo.fechafinal))
    elif nuevo.fechafinal < date.today():
        raise ValidationError(u'\"%s\", \"%s\" Error. La fecha final debe ser mayor o igual a la fecha de hoy' % (nuevo.fechafinal))    
    else:    
        nuevo.save()

    if re.match('(;)|(?i)(ALTER|CREATE|DELETE|DROP|EXEC(UTE){0,1}|INSERT( +INTO){0,1}|MERGE|SELECT|UPDATE|UNION( +ALL){0,1})', nombrepiz):
        Accion.objects.crearAccion(
            usuario,
            "El usuario %s inserto strings peligrosos creando la pizarra %s" % (usuario.username, nombrepiz),
            'w'
            )
    elif re.match('(;)|(?i)(ALTER|CREATE|DELETE|DROP|EXEC(UTE){0,1}|INSERT( +INTO){0,1}|MERGE|SELECT|UPDATE|UNION( +ALL){0,1})', descripcionpiz):
        Accion.objects.crearAccion(
            usuario,
            "El usuario %s inserto strings peligrosos creando la pizarra %s" % (usuario.username, nombrepiz),
            'w'
            )

    #Se registra en el log la creacion de la nueva pizarra
    nombre_usuario = usuario.username
    stringg = "El usuario %s creo la pizarra %s" % (nombre_usuario, unicode(nombrepiz));            
    Accion.objects.crearAccion(
        usuario,
        stringg.encode('utf8'),
        'i')

    #   Creamos la actividad que representa a la pizarra dentro de la pizarra   
    crearActividad(nombrepiz,descripcionpiz,fechacreacion, fechafinal, nuevo, usuario, None)

def modificar(idpiz, nombrepiz, descripcionpiz, fechafinal, usuario):
    """
    Metodo que modifica una pizarra de la base de datos
    In: idpiz, nombrepiz, descripcionpiz, fechafinal
    Out: --
    Autor: Juan Arocha
    Fecha: 27-10-12 Version 1.0
    """
    nueva = Pizarra.objects.filter(idpiz = idpiz)
    nombreB = False
    descripcionB = False
    fechafinalB = False
    if nombrepiz == "":
        nombreB = True
    if descripcionpiz == "":
        descripcionB = True
    if fechafinal == "":
        fechafinalB = True
    
    if not nombreB and not descripcionB and not fechafinalB:
        nuevapiz = nueva.get()
        nuevapiz.nombrepiz = nombrepiz
        nuevapiz.descripcionpiz = descripcionpiz
        nuevapiz.fechafinal = fechafinal
        nuevapiz.save()

        nombre_usuario = usuario.username

        if re.match('(;)|(?i)(ALTER|CREATE|DELETE|DROP|EXEC(UTE){0,1}|INSERT( +INTO){0,1}|MERGE|SELECT|UPDATE|UNION( +ALL){0,1})', nombrepiz):
            Accion.objects.crearAccion(
                usuario,
                "El usuario %s inserto strings peligrosos modificando la pizarra %s" % (usuario.username, nombrepiz),
                'w'
                )
        elif re.match('(;)|(?i)(ALTER|CREATE|DELETE|DROP|EXEC(UTE){0,1}|INSERT( +INTO){0,1}|MERGE|SELECT|UPDATE|UNION( +ALL){0,1})', descripcionpiz):
            Accion.objects.crearAccion(
                usuario,
                "El usuario %s inserto strings peligrosos modificando la pizarra %s" % (usuario.username, nombrepiz),
                'w'
                )
        #Se registra en el log la creacion de la nueva pizarra
	stringg2 = "El usuario %s modifico la informacion de la pizarra %s" % (nombre_usuario, unicode(nombrepiz));            
        Accion.objects.crearAccion(
            usuario,
            stringg2.encode('utf8'), 
            'i')   

def eliminar(idpiz):
    """
    Metodo que elimina una pizarra de la base de datos
    In: idpiz
    Out: --
    Autor: Juan Arocha
    Fecha: 27-10-12 Version 1.0
    """
    from app_actividad.models import Actividad
    
    elem = Pizarra.objects.get(idpiz = idpiz)
    elem.is_active = False
    elem.save()
    usuario = User.objects.get(username=elem.logindueno)
    
    act = Actividad.objects.filter(idpizactividad = idpiz, is_active = True)
    lista = []
    for elemAct in act:
    	elemAct.is_active = False
	elemAct.save()

    #Se registra en el log la creacion de la nueva pizarra
    Accion.objects.crearAccion(
        usuario,
        "El usuario %s elimino la pizarra %s" % (usuario.username, str(elem.nombrepiz)), 
        'w')       
    

def obtenerPizarra(idpiz):
    """
    Metodo que retorna un diccionario con los datos de una pizarra asociada con el idpiz
    In: idpiz
    Out: pizarra
    Autor: Juan Arocha
    Fecha: 27-10-12 Version 1.0
    """
    pizarra = {}
    elem = Pizarra.objects.get(idpiz = idpiz)
    pizarra['nombre'] = elem.nombrepiz
    pizarra['descripcion'] = elem.descripcionpiz
    pizarra['fechacreacion'] = elem.fechacreacion
    pizarra['fechafinal'] = elem.fechafinal
    
    return pizarra

def obtener_pizarras(usuario):
	"""
	Metodo que obtiene las pizarras del usuario logueado
	In: usuario
	Out: lista
	Autor: Juan Arocha
	Modificaciones: Ivan Travecedo
	Fecha: 6-12-12 Version 1.1
	"""
	from app_actividad.models import colaboradores
	piz = Pizarra.objects.all()
	listaPizarras = []
	for elem in piz:
		listaColab = colaboradores(elem.idpiz)
		if usuario in listaColab:
			listaPizarras.append(elem)
	return listaPizarras

app_pizarras/forms.py
# -*- coding:utf-8 -*-
from django import forms
from django.core.exceptions import ValidationError
import re

def validate_nombrepiz(value):
    """
    Metodo que valida el formato del nombre de la pizarra. Expresion regular: '^[a-zA-Z]+$
    In: value
    Out: --
    Autor: Mary Ontiveros
    Fecha: 7-11-12
    """
    if re.match('^[a-zA-Z]+$',value)==None:
        raise ValidationError(u'\"%s\" no es un nombre valido' % value)

def validate_descripcionpiz(value):
    """
    Metodo que valida el formato de la descripcion de la pizarra. Expresion regular: '^[a-zA-Z]+$
    In: value
    Out: --
    Autor: Mary Ontiveros
    Fecha: 7-11-12
    """
    if re.match('^\w+$',value)==None:
        raise ValidationError(u'agregue una descripcion')

class CrearPizarraForm(forms.Form):
    """
    Form para crea pizarra
    In: forms.Form
    Out: --
    Autor: Juan Arocha
    Fecha: 7-11-12 Version 1.0
    """
    nombre = forms.CharField(max_length=50)
    descripcion = forms.CharField(max_length=100, widget=forms.Textarea)
    fecha_inicio = forms.DateField()
    fecha_final = forms.DateField()

class ModificarPizarraForm(forms.Form):
    """
    Form para modificar pizarra
    In: forms.Form
    Out: --
    Autor: Juan Arocha
    Fecha: 7-11-12 Version 1.0
    """
    input_formats = ('%d/%m/%Y',)
    nombre = forms.CharField(max_length=50)
    descripcion = forms.CharField(max_length=100, widget=forms.Textarea)
    fecha_final = forms.DateField(input_formats=input_formats)

templates/app_pizarras/crear_pizarra.html
<script>
  calendarios();
</script>
<div id="errores_crear_pizarra" class="errores">
  *Todos los campos son requeridos
</div>
<form action="{% url "app_pizarras:crear_pizarra" %}" id="pizarraForm" method="post">
  {% csrf_token %}
  <fieldset  id="body">
    {{ form.as_p }}
  </fieldset>
</form>

templates/app_pizarras/listar.html
{% extends "app_usuarios/template.html" %}
{% load staticfiles %}
{% load dajaxice_templatetags %}
{% block titulo %}Pared{% endblock titulo %}
{% block css %}
<link href="{% static "css/pared_style.css" %}" rel="stylesheet" type="text/css"/>
{% endblock css %}

{% block cuerpo %}
{% if not lista %}
<div id="noElems">No hay pizarras.</div>
{% endif %}
<style>
    .mostrar {
        color: #ffffff
        font-size: 14px;
        font-style: italic;
    }

.detalles{

        position: absolute;
        background-color: rgb(240, 230, 140);
        font-size: 14px;
        font-family: Helvetica;
        padding: 10px;
    }
</style>
<script type="text/javascript" src="{% static "javascript/jquery.paginatetable.js" %}"></script>
    <script src="../../javascript/jquery.min.js"></script>
    <script>
        $(document).ready(function(){

            $(".detalles").hide();
            $(".mostrar").hover(function(){
                $(this).siblings('.detalles').toggle();

            });
        });
    </script>
    <script>
        $(document).ready(function(){
        });
    </script>
<script>
function divSubmit(div){
  lista = div.getElementsByTagName("form");
  for (var i = 0; i<lista.length; ++i){
    var elem = lista[i]
    if (elem.id == "visualizarPizarra")
      elem.submit();
  }
}

$(document).ready(function () {
  $('#pared').paginateTable({ rowsPerPage: 3 });

  $(".pizarra").click(function(e) {
    if (e.target.id != "modi") {
      divSubmit(this);
    }
  });
});
</script>
<table id="pared">
  <tbody>
    {% for object in lista%}

    <tr>

      <td>
          <span class="mostrar">Mostrar Detalles</span>
	        <span class="detalles"> <br/>Creador: "{{object.logindueno.first_name}}  {{object.logindueno.last_name}}"<br/>
			Fecha: "{{object.fechacreacion}} - {{object.fechafinal}}" <br/>
			Participantes:
                {% for key, values in colaboradores.items %}
                {% ifequal key object.idpiz %}
                    <ul>
                        {% for num in values %}
                            <li>{{ num }}</li>
                        {% endfor %}
                    </ul>
                {%endifequal%}
                {% endfor %}

		</span>
        <div class="pizarra">
          <div id="cabeza">
            <div id="titulo">
              {{object.nombrepiz}}
            </div>
            <form action="{% url "app_pizarras:eliminar_pizarra" %}" method="post" onsubmit="if(!confirm('Seguro desea eliminar esta pizarra?')) return false" style="width: 25px;float: right;">
              {% csrf_token %}
              <input type="hidden" name="idpiz" value="{{object.idpiz}}"/>
              <input class="borrar" type="submit" value=""/>
            </form>
            <form action="{% url "app_pizarras:modificar_form" %}" onsubmit="return false;" method="post" style="width: 25px;float: right;">
              {% csrf_token %}
              <button type="submit" class="modi" id="modi" onclick="Dajaxice.app_pizarras.modificarPizarraAjax(my_js_callbackModificarPizarra, {'id_pizarra' : {{object.idpiz}}}); return false;"></button>
            </form>
            <form id="visualizarPizarra" action="{% url "app_pizarras:visualizar_pizarra" %}" method="post">
              {% csrf_token %}
              <input type="hidden" name="idpiz" value="{{object.idpiz}}"/>  
            </form>  
          </div>
          <div id="content">
            {{object.descripcionpiz}}<br><br>
          </div>
            </div>
        </div>
      </td>

    </tr>

    {% endfor %}
  </tbody>
  <div class='pager'>
    <a href='#' alt='Previous' class='prevPage'><img src="{% static "images/leftArrow.png" %}" style="height: 30px"/></a>
    <a href='#' alt='Next' class='nextPage'><img src="{% static "images/rightArrow.png" %}" style="height: 30px"/></a>
  </div>
</table>
{% endblock cuerpo %}

templates/app_pizarras/modificar_pizarra.html
<script type="text/javascript">
  calendarios();
</script>
<div id="errores_modificar_pizarra" class="errores"/>
<form id="modificarPizarraForm" action="{% url "app_pizarras:modificar_pizarra" %}" method="post">
  {% csrf_token %}
  <fieldset id="body">
    <input type="hidden" name="idpiz" value="{{id_pizarra}}" />
    <fieldset>
      <label for="nombrepiz">Nombre Pizarra</label>
      <input type="text" name="nombre" id="id_nombre" value="{{lista.0}}"/>
    </fieldset>
    <fieldset>
      <label for="descripcion">Descripción Pizarra</label>
      <textarea class="input-large" rows= "5" type="text" name="descripcion" id="id_descripcion">{{lista.1}} </textarea>
    </fieldset>
    <fieldset>
      <div>Fecha de Creacion</div>
      <div>{{ lista.2 }}</div>
      <input type="hidden" name="fecha_creacion" id="id_fecha_creacion" value="{{ lista.2 }}"/>
    </fieldset>
    <fieldset>
      <label for="fechafinal">Fecha de Finalización</label>
      <input type="text" name="fecha_final" id="id_fecha_final" value="{{ lista.3 }}"/>
    </fieldset>
  </fieldset>
</form>

templates/app_pizarras/vistaPizarra.html
{% extends "app_usuarios/template.html" %}
{% load url from future %}
{% load staticfiles %}
{% block titulo %}Pizarra "{{pizarra.nombrepiz}}"{% endblock titulo %}
{% block css %}
<link href="{% static "css/vistaPizarra_style.css" %}" rel="stylesheet" type="text/css"/>
{% endblock css %}
{% block botones %}
<form action="{% url 'app_pizarras:eliminar_pizarra' %}" onsubmit="if(!confirm('Seguro desea eliminar esta pizarra?')) return false"  style="margin: 0;" method="post">
  {%csrf_token%}
  <input type="hidden" name="idpiz" value="{{pizarra.idpiz}}"/>
  <input type="image" class="opcionesIzq" src="{% static "img/rem.png" %}" style="height: 20px;"/>
</form>
<a id="crearActividad" onclick="Dajaxice.app_actividad.crearActividadForm(my_js_callbackActividad, {'data': {{pizarra.idpiz}}});" class="opcionesDer" href="#">Crear Actividad</a>
{% endblock botones %}
{% block cuerpo %}
<div id="ventanaActividad" style="display:none"></div>
<div id="formActividad" style="display:none"></div>
<style>
  #formActividad textarea, input[type="text"]{
    width:92%;
    border:1px solid #899caa;
    border-radius:3px;
    -moz-border-radius:3px;
    color:#3a454d;
    font-weight:bold;
    padding:8px 8px;
    box-shadow:inset 0px 1px 3px #bbb;
    -webkit-box-shadow:inset 0px 1px 3px #bbb;
    -moz-box-shadow:inset 0px 1px 3px #bbb;
    font-size:10px;
  }

  .participante{
    background: transparent; 
    border: none; 
    cursor: pointer;
  }

  .participante:hover{
    color: white;
  }
</style>
<script>
</script>
<div id="columna">
  <table>
    <tr>
      <td>
        <h>Pizarra</h></br>
        {{pizarra.nombrepiz}}
      </td>
    </tr>
    <tr>
      <td>
        <h>Creador</h></br>
          <form action="{% url 'app_usuarios:perfil_usuario' %}" method="post">
            {% csrf_token %}
            <input type="hidden" value="{{pizarra.logindueno.username}}" name="usuario"/>
            <input type="submit" class="participante" value="{{pizarra.logindueno.first_name}} {{pizarra.logindueno.last_name}}"/>
          </form>
      </td>
    </tr>
    <tr>
      <td>
        <h>Descripcion</h></br>
        {{pizarra.descripcionpiz}}
      </td>
    </tr>
    <tr>
      <td>
        <h>Fecha de inicio</h></br>
        {{pizarra.fechacreacion}}
      </td>
    </tr>
      <td>
        <h>Fecha de finalizacion</h></br>
        {{pizarra.fechafinal}}
      </td>
    </tr>
    <tr>
      <td>        
        <h>Participantes</h></br>
        <div id="lista"
          {%for elem in colaboradores %}
          <form action="{% url 'app_usuarios:perfil_usuario' %}" method="post">
            {% csrf_token %}
            <input type="hidden" value="{{elem.username}}" name="usuario"/>
            {% ifnotequal elem.first_name "" %}
            {% ifnotequal elem.last_name "" %}
            <input type="submit" class="participante" value="{{elem.first_name}} {{elem.last_name}}"/>
            {%endifnotequal%}
            {%endifnotequal%}
            {% ifequal elem.first_name "" %}
            {% ifequal elem.last_name "" %}
            <input type="submit" class="participante" value="{{elem.username}}"/>
            {%endifequal%}
            {%endifequal%}
          </form>
          {%endfor%}
        </div>
      </td>
    </tr>
  </table>
</div>
<div id="arbol">
  <div id="vistas" style="">
    Vistas...
  </div>

  <div id="vistasDropDown" style="" >
    <form action="{% url 'app_pizarras:visualizar_pizarra' %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="idpiz" value="{{pizarra.idpiz}}"/>
      <input type="submit" value="Jerarquica"/>
    </form>
    <form action="{% url 'app_pizarras:orden_cronologico' %}" method="post">
      {% csrf_token %}
      <input type="submit" value="Cronologica"/>
      <input type="hidden" name="idpiz" value="{{pizarra.idpiz}}"/>
    </form>
    <form action="{% url 'app_pizarras:orden_estados' %}" method="post">
      {% csrf_token %}
      <input type="submit" value="Por estado"/>
      <input type="hidden" name="idpiz" value="{{pizarra.idpiz}}"/>
    </form>
    <form action="{% url 'app_pizarras:orden_avance' %}" method="post">
      {% csrf_token %}
      <input type="submit" value="Por avance"/>
      <input type="hidden" name="idpiz" value="{{pizarra.idpiz}}"/>
    </form>
  </div>
  <form action="{% url 'app_actividad:visualizar_actividad' %}" id="visualizarActividad" method="post">
    {% csrf_token %}
    <input id="inputAct" type="hidden" value="abc" name="idact"/>
  </form>
  <div id="log"></div>
</div>
{% endblock cuerpo%}