app_log/urls.py
from django.conf.urls import patterns, url

from app_log import views as views_log
from django.contrib.auth import views as views_admin

urlpatterns = patterns('',
    url(r'^consultar_log/', views_log.visualizar_accion_user, name='visualizar_log_user'),
)

app_usuarios/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth import views as views_admin

from rest_framework.urlpatterns import format_suffix_patterns

from app_usuarios import views as views_usuarios
from app_usuarios import rest_views as rest_views_usuarios

urlpatterns = patterns('',
    url(r'^crear_usuario/', views_usuarios.crear_usuario, name='crear_usuario'),
    url(r'^registrar_visitante/', views_usuarios.registrar_visitante, name='registrar_visitante'),
    url(r'^cambiar_contrasena/', views_usuarios.cambiar_contrasena, name='cambiar_contrasena'),
    url(r'^listar_usuarios/', views_usuarios.listar_usuarios, name='listar_usuarios'),
    url(r'^modificar_usuario/', views_usuarios.modificar_usuario, name='modificar_usuario'),
    url(r'^modificar_form/', views_usuarios.modificar_form, name='modificar_form'),
    url(r'^eliminar_usuario/', views_usuarios.eliminar_usuario, name='eliminar_usuario'),
    url(r'^resetpassword/passwordsent/$', views_admin.password_reset_done),
    url(r'^resetpassword/$', views_admin.password_reset, name = "password_reset"),
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', views_admin.password_reset_confirm),
    url(r'^reset/done/$', views_admin.password_reset_complete),
    url(r'^cerrar_sesion/', views_usuarios.logout_view, name='logout_view'),
    url(r'^perfil_usuario/',views_usuarios.perfil_usuario, name='perfil_usuario'),
    url(r'^login/(?P<nombre_usuario>\w+)/(?P<clave>[\w\d]+)/$', rest_views_usuarios.Login.as_view(), name='rest_login'),
    url(r'^crear_usuario_rest/', rest_views_usuarios.UserProfileList.as_view(), name='rest_create_user'),
    #url(r'^login/(?P<nombre_usuario>\w+)/(?P<clave>[\w\d]+)/$', rest_views_usuarios.Login.as_view(), name='rest_login'),
)

urlpatterns = format_suffix_patterns(urlpatterns)

proyecto_pizarras/urls.py
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from dajaxice.core import dajaxice_autodiscover, dajaxice_config

from app_actividad.models import Actividad
from app_usuarios import views as views_usuarios
from app_usuarios.models import UserProfile
from app_usuarios.models import UserProfile
from app_pizarras.models import Pizarra
from app_log.models import Accion
from app_comentarios.models import Comentario

#admin.site.register(UserProfile)
admin.site.register(Pizarra)
admin.site.register(Actividad)
admin.site.register(Comentario)
admin.site.register(Accion)
admin.autodiscover()
dajaxice_autodiscover()

urlpatterns = patterns('',
    url(r'^admin/',                                            include (admin.site.urls)),
    url(r'^account/',                                          include ('django.contrib.auth.urls')),
    url(r'^$', views_usuarios.login_if, name='login_usuario'),
    url(r'^usuarios/',                                         include ('app_usuarios.urls', namespace="app_usuarios")),
    url(r'^pizarras/',                                         include ('app_pizarras.urls', namespace="app_pizarras")),
    url(r'^actividad/',                                        include ('app_actividad.urls', namespace="app_actividad")),
    url(r'^comentarios/',                                      include ('app_comentarios.urls', namespace="app_comentarios")),
    url(dajaxice_config.dajaxice_url,                          include ('dajaxice.urls')),
    url(r'^log/',                                              include ('app_log.urls', namespace="app_log")),
)

urlpatterns += staticfiles_urlpatterns()

app_usuarios/models.py
#coding=utf-8

import re
import datetime
from django.db import models
from django.contrib.auth.models import User, Group, Permission, UserManager, AnonymousUser
from django.utils.encoding import smart_str
from django.core.exceptions import ValidationError
from app_log.models import ManejadorAccion, Accion

class ManejadorUsuario(UserManager):

    def crear_colaborador(self, data, usuario):
        """
        Crea un colaborador con los datos proporcionados
        In: self, data, usuario
        Out: --
        Autor: German Leon
        Fecha: 4-11-12 Version 1.0
        """
        print "Entramos a crear_colaborador"
        u = User.objects.create_user(
            username = data['nuevo_nombre_usuario'],
            email    = data['nuevo_correo'],
        )
        u.set_password(data['nueva_password'])
        u.first_name = data['nuevo_nombre']
        u.last_name  = data['nuevo_apellido']

        u.save()

        #   Se crea el UserProfile 
        up = UserProfile.objects.create(user=u, telefono= data["nuevo_telefono"])
        #   Agregamos el usuario recien creado al grupo de los colaboradores
        u.groups.add(Group.objects.get(name="Colaboradores"))

        #Se registra en el log que "usuario" creo a un nuevo colaborador
        if not usuario.username == '':
            if re.match('(;)|(?i)(ALTER|CREATE|DELETE|DROP|EXEC(UTE){0,1}|INSERT( +INTO){0,1}|MERGE|SELECT|UPDATE|UNION( +ALL){0,1})', u.first_name):
                Accion.objects.crearAccion(
                    usuario,
                    "El usuario %s inserto strings peligrosos creando al usuario %s" % (usuario.username, u.username),
                    'w'
                    )
            elif re.match('(;)|(?i)(ALTER|CREATE|DELETE|DROP|EXEC(UTE){0,1}|INSERT( +INTO){0,1}|MERGE|SELECT|UPDATE|UNION( +ALL){0,1})', u.last_name):
                    Accion.objects.crearAccion(
                    usuario,
                    "El usuario %s inserto strings peligrosos creando al usuario %s" % (usuario.username, u.username),
                    'w'
                    )
            Accion.objects.crearAccion(
                usuario, 
                "El usuario %s agrego a %s" % (usuario.username, u.first_name),
                'i')

            Accion.objects.crearAccion(
                usuario,
                "Se creo una instancia de usuario con los valores Nombre: %s, Apellido: %s, Email: %s, Tlf: %s" % (u.first_name, u.last_name, u.email, up.telefono),
                'd'
                )

        return up  

    def crear_administrador(self, usuario, datos):
        """
        Metodo para crear un Administrador
        In: self, usuario, datos
        Out: --
        Autor: German Leon
        Fecha: 4-11-12 Version 1.0
        """
        #   Creamos un usuario como en crear_colaborador pero con privilegios de administador
        print "Asignandole privilegios de administrador al usuario recien creado ..."
        up = self.crear_colaborador(datos, usuario)
        #   Agregamos al usuario recien creado al grupo de administradores
        up.user.groups.add(Group.objects.get(name="Administradores"))

    def modificar(self, nombre_usuario, nombre, apellido, telefono, correo, usuario):
        """
        Crea un administrador con sus respectivos permisos
        In: self, nombre_usuario, nombre, apellido, telefono, correo 
        Out: --
        Autor: German Leon
        Fecha: 4-11-12 Version 1.0
        """
        modificado   = User.objects.get(username = nombre_usuario)
        nuevo        = User.objects.filter(username = nombre_usuario)
        nuevoProfile = UserProfile.objects.filter(user=nuevo)
        telefonoB    = False
        correoB      = False
        if correo == "":
            correoB = True
        if telefono == "":
            telefonoB = True

        if not correoB and not telefonoB:
            nuevo.update(first_name=nombre, last_name= apellido, email = correo)
            nuevouser = nuevoProfile.get()
            nuevouser.telefono = telefono
            nuevouser.save()
            print nuevoProfile.values()

            if re.match('(;)|(?i)(ALTER|CREATE|DELETE|DROP|EXEC(UTE){0,1}|INSERT( +INTO){0,1}|MERGE|SELECT|UPDATE|UNION( +ALL){0,1})', nombre):
                Accion.objects.crearAccion(
                usuario,
                "El usuario %s inserto strings peligrosos modificando al usuario %s" % (usuario.username, modificado.username),
                'w'
                )
            elif re.match('(;)|(?i)(ALTER|CREATE|DELETE|DROP|EXEC(UTE){0,1}|INSERT( +INTO){0,1}|MERGE|SELECT|UPDATE|UNION( +ALL){0,1})', apellido):
                Accion.objects.crearAccion(
                usuario,
                "El usuario %s inserto strings peligrosos creando al usuario %s" % (usuario.username, modificado.username),
                'w')

            #Se agrega en el log que "usuario" edito su perfil
            #si el usuario esta modificando su propio perfil
            if (usuario.username == modificado.username):
                Accion.objects.crearAccion(
                    usuario,
                    "El usuario %s modifico la informacion de su perfil" % usuario.username,
                    'i')
            else:
                Accion.objects.crearAccion(
                usuario,
                "El usuario %s modifico la informacion de %s" % (usuario.username, modificado.username),
                'i')


    def eliminar(self, nombre_usuario, nombre_userloggeado):
        usuario = User.objects.get(username=nombre_usuario)
        usuario.is_active = False
        usuario.save()

        #si se intenta eliminar a un usuario que es administrador se considera
        #a ese log como warning, si se elimina a un colaborador el log es de tipo info.
        if usuario.groups.filter(name='Administradores').exists():
            Accion.objects.crearAccion(
                usuario,
                "El usuario %s elimino al administrador %s" % (nombre_userloggeado, nombre_usuario),
                'w')
        else:            
            Accion.objects.crearAccion(
                usuario,
                "El usuario %s elimino a %s" % (nombre_userloggeado, nombre_usuario),
                'i')


class UserProfile(models.Model):
    """
    Clase UserProfile que extiende los datos que se definen en la clase User de Django
    Nota: Deprecado esta manera de extender User esta deprecada en Django 1.5
    Autor: German Leon
    Fecha: 4-11-12 Version 1.0
    """
    #   Campo obligatorio para poder extender
    user = models.OneToOneField(User)

    #   Campos adicionales del perfil del Usuario
    telefono = models.CharField(max_length=15)

    #   El Manager de UserProfile sera el ManejadorUsuario que definimos
    objects = ManejadorUsuario()
    
    def save(self, *args, **kwargs):
        self.telefono = smart_str(self.telefono, encoding="utf-8")
        if re.match('^[0-9]+[-]?[0-9]+$', self.telefono) == None:
            raise ValidationError(u'\"%s\" Error. El telefono solo puede estar compuesto por numeros' % self.telefono)
        else:    
        	super(UserProfile, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.user.username + ", " + self.telefono

app_usuarios/forms.py
#coding=utf-8

import re

from django import forms
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.contrib.auth.models import User

def validate_user(value):
	"""
	Metodo para validar el username. Expresion regular a cumplir: '^[a-zA-Z]+[a-zA-Z-_.0-9]+$'
	In: value
	Autor: Mary Ontiveros
	Fecha: 8-11-12 Version 1.0
	"""
	if re.match('^[a-zA-Z\xe1\xe9\xed\xf3\xfa\xc9\xcd\xd3\xda\xc1\xd1\xf1]+[a-zA-Z-_.0-9\xe1\xe9\xed\xf3\xfa\xc9\xcd\xd3\xda\xc1\xd1\xf1]+$',value)==None:
		raise ValidationError(u'\"%s\"no es un usuario válido' % value)

def validate_nombre(value):
	"""
	Metodo para validar el nombre del usuario. Expresion regular a cumplir: '^[a-zA-Z]+$'
	In: value
	Autor: Mary Ontiveros
	Fecha: 8-11-12 Version 1.0
	"""
	if re.match('(^$|^[A-Za-z0-9\xe1\xe9\xed\xf3\xfa\xc9\xcd\xd3\xda\xc1\xd1\xf1\¿\!\¡\:\,\.\-\ç\ñáéíóú\(\)\"\'\äëïöüàèìòù\s]*$)',value)==None:
		raise ValidationError(u'\"%s\" no es un nombre válido, debe estar compuesto solo por letras.' % value)

def validate_apellido(value):
	"""
	Metodo para validar el apellido de un usuario. Expresion regular: '^[a-zA-Z]+$'
	In: value
	Autor: Mary Ontiveros
	Fecha: 8-11-12 Version 1.0
	"""
	if re.match('(^$|^[a-zA-Z\'\xe1\xe9\xed\xf3\xfa\xc9\xcd\xd3\xda\xc1\xd1\xf1]+$)',value)==None:
		raise ValidationError(u'\"%s\" no es un apellido válido, debe estar compuesto solo por letras' % value)

def validate_telefono(value):
	"""
	Metodo para validar el teléfono de un usuario. Expresion regular: '^[0-9]+[-]?[0-9]+$'
	In: value
	Autor: Mary Ontiveros
	Fecha: 8-11-12 Version 1.0
	"""
	if re.match('^[0-9]+[-]?[0-9]+$', value) == None:
		raise ValidationError(u'\"%s\" no es un teléfono válido' % value)

def validate_password(value):
	"""
	Metodo para validar la contraseña de un usuario. 
	In: value
	Autor: Mary Ontiveros
	Fecha: 8-11-12 Version 1.0
	"""
	if len(value)<6:
		raise ValidationError(u' Clave Invalida')
	      
def validate_unico(value):
	"""
	Metodo para validar que solo exista un usuario con ese username
	In: value
	Autor: Mary Ontiveros
	Fecha: 8-11-12 Version 1.0
	"""
	if not User.objects.filter(username = value):
		pass
	else:
		raise ValidationError(u'Ya existe usuario con ese Nombre')


class LoginForm (forms.Form):    
    """
    Form para registrarse en el sistema
    In: forms.Form
    Autor: German Leon
    Fecha: 5-11-12 Version 1.0
    """	

    class Meta:
            model = User

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['nombre_usuario'].error_messages = {'required': 'El nombre de usuario es obligatorio'}
        self.fields['password'].error_messages = {'required': 'La clave es obligatoria'}

    nombre_usuario = forms.CharField(max_length=30, validators=[validate_user])
    password = forms.CharField(widget=forms.PasswordInput, validators=[validate_password])
    
    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        username = cleaned_data.get("nombre_usuario")
        password = cleaned_data.get("password")

        if username and password:
            usuario = authenticate(username=username, password=password)
            if usuario is None:
                raise ValidationError(u'Error en el nombre de usuario o contraseña')
        return cleaned_data        

class CrearUsuarioForm(forms.Form):
    """
    Form para crear un nuevo usuario en el sistema
    In: forms.Form
    Autor: German Leon
    Fecha: 8-11-12 Version 1.0
    """
    nuevo_nombre_usuario = forms.CharField(label="Nombre de usuario",max_length=30, validators=[validate_unico,validate_user])	
    nueva_password = forms.CharField(label="Contraseña", widget=forms.PasswordInput, max_length=15,validators=[validate_password])
    nuevo_correo = forms.EmailField(label="Dirección de correo electrónico", max_length=50, error_messages={'invalid': ('La dirección de correo es inválida')})
    nuevo_nombre = forms.CharField(label="Nombre", max_length=80,validators=[validate_nombre])
    nuevo_apellido = forms.CharField(label="Apellido", max_length=20,validators=[validate_apellido])
    nuevo_telefono = forms.CharField(label="Número de teléfono", max_length=15,validators=[validate_telefono])
    nuevo_administrador = forms.BooleanField(label="Administrador", initial=False, required = False)

class RegistrarVisitanteForm(forms.Form):
    """
    Form para registrar un usuario desde afuera del sistema
    In: forms.Form
    Autor: German Leon
    Fecha: 28-2-13 Version 1.0
    """
    nuevo_nombre_usuario = forms.CharField(label="Nombre de usuario",max_length=30, validators=[validate_unico,validate_user])	
    nueva_password = forms.CharField(label="Contraseña", widget=forms.PasswordInput, max_length=15,validators=[validate_password])
    nuevo_correo = forms.EmailField(label="Dirección de correo electrónico", max_length=50, error_messages={'invalid': ('La dirección de correo es invalida')})
    nuevo_nombre = forms.CharField(label="Nombre", max_length=80,validators=[validate_nombre])
    nuevo_apellido = forms.CharField(label="Apellido", max_length=20,validators=[validate_apellido])
    nuevo_telefono = forms.CharField(label="Número de teléfono", max_length=15,validators=[validate_telefono])

class ModificarUsuarioForm(forms.Form):
    """
    Form para modificar un usuario que ya este registrado en el sistema
    In: forms.Form
    Autor: German Leon
    Fecha: 8-11-12 Version 1.0
    """
    nombre = forms.CharField(max_length=80,validators=[validate_nombre], required=False)
    apellido = forms.CharField(max_length=20,validators=[validate_apellido], required=False)
    telefono = forms.CharField(max_length=15,validators=[validate_telefono])
    correo = forms.EmailField(max_length=50, error_messages={'invalid': ('La dirección de correo es inválida')})

class CambiarContrasenaForm(forms.Form):
    """
    Form para cambiar la contraseña de un usuario
    In: forms.Form
    Autor: German Leon
    Fecha: 20-11-12 Version 1.0
    """
    contrasena1 = forms.CharField(label = "Nueva contraseña", widget=forms.PasswordInput, max_length=15,validators=[validate_password])
    contrasena2 = forms.CharField(label = "Repita su nueva contraseña", widget=forms.PasswordInput, max_length=15,validators=[validate_password])

templates/app_usuarios/lista_usuarios.html
{% extends "app_usuarios/template.html" %}
{% block titulo %}Listar usuarios{% endblock titulo %}
{% block cuerpo %}

<table class="tabla">
  <tr>
    <th style="width:200px !important;">Nombre de usuario</th>
    <th>Nombre</th>
    <th>Apellido</th>
    {% if perms.app_usuarios.change_userprofile %} 
    <th>Modificar</th>
    {% endif %}
    {% if perms.app_usuarios.delete_userprofile %}
    <th>Eliminar</th>
    {% endif %}
  </tr>
  {% for objeto in lista%}
  <tr>
    <td>
      {{objeto.username}}
    </td>
    <td>
      {{objeto.first_name}}
    </td>
    <td>
      {{objeto.last_name}}
    </td>
    <td>
      <form action="{% url "app_usuarios:modificar_form" %}" onsubmit="return false;" method="post">
        {% csrf_token %}
        {% if perms.app_usuarios.change_userprofile %}
          <button type="submit" class="modificarUsuario" onclick="Dajaxice.app_usuarios.modificarUsuarioAjax(my_js_callbackModificarUsuario, {'nombre_usuario' : {{objeto.id}}});">Modificar</button>
        {% endif %}
      </form>
    </td>
    <td>
      {% if perms.app_usuarios.delete_userprofile %}
      <form action="{% url "app_usuarios:eliminar_usuario" %}" method="post" onsubmit="if (!confirm('Seguro desea elimimar este usuario?')) return false">
        {% csrf_token %}
        <input name="nombre_usuario" type="hidden" value="{{objeto.username}}"/>
        <input type="submit" value="Eliminar"/>
      </form>
      {% endif %}
    </td>
  </tr>
  {% endfor %}
</table>
</br>
{% if perms.app_usuarios.change_userprofile %}
<button id="crearUsuario" onclick="Dajaxice.app_usuarios.crearUsuarioAjax(my_js_callbackUsuario);" style="cursor:pointer;">Crear Usuario</button>
{% endif %}
{% endblock cuerpo %}

templates/app_usuarios/login.html
{% extends "app_usuarios/template.html" %}
{% load staticfiles %}
{% block titulo %}
Inicio de sesión
{% endblock %}
{% block css %}
<link href="{% static "css/inicio_style.css" %}" rel="stylesheet" type="text/css"/>
{% endblock css %}
{% block rightHeader %}
<a style="color:white;" href="{% url "app_usuarios:registrar_visitante" %}">
  <div id="nombre">
    Registrarse
  </div>
</a>
{% endblock rightHeader %}
{% block herramientas %}{% endblock herramientas %}
{% block cuerpo %}
<script>
  $("#forgot").click(function() {
    $("#recuperar").dialog({
      modal:true,
      position: { my: "center", at: "top", of: window },
      dialogClass: 'style_Dialog',
      title: "Recuperar contraseña",
      buttons: {
        "Enviar": function(){
          var mail = $("#");

          return true;
        },
        Cancelar: function() {
          $(this.)dialog("close");
        }
      }
    });
  })
</script>

<div id="tutorial" >
  ¿Cómo usar el Proyecto Pizarra?<br>
  <iframe width="400" height="225" src="http://www.youtube.com/embed/-5e0BKrXGpA" frameborder="0" allowfullscreen></iframe>
</div>
<!-- LOGIN BOX -->
<div id="loginBox">                
  <form action="{% url "login_usuario" %}" method="post" id="loginForm">
    <fieldset id="body">
        {% csrf_token %}
        {{ form.as_p }}
      <input type="submit" id="login" value="Iniciar Sesión" />
    </fieldset>
    <span><a id="forgot" href="{% url 'app_usuarios:password_reset' %}">¿Olvidaste tu contraseña?</a></span>
  </form>
</div>

{% endblock %}

templates/app_usuarios/modificar_usuario.html
<div id ="errores_modificar_usuario" class="errores">Todos los campos son requeridos</div>
<form action="{% url "app_usuarios:modificar_usuario" %}" id="modificarUsuarioForm" method="post">
  {% csrf_token %}
  <fieldset id="body">
    <input id="id_nombre_usuario" name="nombre_usuario" type="hidden" value="{{nombre_usuario}}"/>
    <fieldset>
      <label for="nombre"> Nombre</label>
      {{ form.nombre.errors }}
      <input type="text" name="nombre" id="id_nombre" value="{{lista.0}}" />
    </fieldset>
    <fieldset>
      {{ form.apellido.errors }}
      <label for="apellido">Apellido</label>
      <input type="text" name="apellido" id="id_apellido" value="{{lista.1}}" />
    </fieldset>
    <fieldset>
      <label for="correo">Correo</label>
      {{ form.correo.errors }}
      <input type="text" name="correo" id="id_correo" value="{{lista.2}}"/>
    </fieldset>
    <fieldset>
      <label for="telefono">Teléfono</label>
      {{ form.telefono.errors }}
      <input type="text" name="telefono" id="id_telefono" value="{{lista.3}}" />
    </fieldset>
  </fieldset>
</form>

templates/app_usuarios/template.html
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    {% load staticfiles %}
    {% load dajaxice_templatetags %}
    {% dajaxice_js_import %}
    <title>
      {% block titulo %}
      Proyecto de pizarras
      {% endblock titulo%}
    </title>
    <!-- CSS -->
    <link href="{% static "css/template_style.css" %}" rel ="stylesheet" type="text/css"/>
    <link href="{% static "css/pared_style.css" %}"    rel ="stylesheet" type="text/css"/>
    <link href="{% static "css/style_dialog.css" %}"   rel ="stylesheet" type="text/css"/>
    <link href="{% static "css/calendario.css" %}"     rel ="stylesheet" type="text/css"/>
    {% block css %}
    {% endblock css %}
    <!-- JAVASCRIPT -->
    <script type="text/javascript" src="{% static "javascript/jquery-1.8.2.min.js"%}"></script>
    <script type="text/javascript" src="{% static "javascript/jquery-ui-1.9.1.custom.min.js"%}"></script>
    <script type="text/javascript" src="{% static "javascript/jquery-ui-1.9.1.custom.js"%}"></script>
    <script type="text/javascript" src="{% static "javascript/validaciones.js"%}"></script>
    <script type="text/javascript" src="{% static "javascript/funciones.js"%}"></script>
    <script type="text/javascript" src="{% static "javascript/arbol.js"%}"></script>
    <script type="text/javascript" src="{% static "javascript/jit.js"%}"></script>
    <!-- Bloques para javascript y css particulares-->
    {% block javascript %}
    <script>
      $(document).ready(function(){
        dialog();
        barraUsuario();
        $("#vistasDropDown").hide();
        $("#vistas").click(function(){
          $("#vistasDropDown").toggle();
        });
      });
    </script>
    {% endblock javascript %}
  </head>

  <body onload="
    var arbol = document.getElementById('stringJson').value;
    init(arbol);" >
    <input type="hidden" id="stringJson" value="{{arbol}}"/>
    <!-- borde es el contenedor de la pagina-->
    <div id="borde">
      <!-- Encabezado de la pagina-->
      <div id="header">
        <a href="{% url "app_pizarras:listar_pizarra" %}"><img id="logo" src="{% static "images/logo_front.png" %}"/></a>
        {% block rightHeader %}
        {% if user.is_authenticated %}
        <div id="nombre">
          {{user.first_name}} {{user.last_name}}
        </div>
        {% endif %}
        {% endblock rightHeader %}
      </div>
      <!-- -->
      <div id="main">

        {% block herramientas %}

        <div id="herramientas">
          <a id="crearPizarra" onclick="Dajaxice.app_pizarras.crearPizarraForm(my_js_callbackPizarra);" class="opcionesDer" href="#">Nueva Pizarra</a>
          <a id="mis_pizarras" class="opcionesDer" href="{% url "app_pizarras:listar_pizarra" %}">Mis pizarras</a>
          <a id="listarUsuarios" class="opcionesDer" href="{% url "app_usuarios:listar_usuarios" %}">Listar usuarios</a>
          {% block botones %}{% endblock botones %}
        </div>
        <div id="opcionesUsuario">
        {% for group in user.groups.all %}
          {% if group.name == 'Administradores'%}
          <div class="opcionVer">
          <a  href="{% url "app_log:visualizar_log_user" %}"> Visualizar Log</a>
          </div>
        {% endif %}
        {%endfor %}
          <div class="opcionVer"><a href="{% url "app_pizarras:listar_pizarra" %}">Mis pizarras</a></div>
          <div class="opcionVer"><a id="editarPerfil" onclick="Dajaxice.app_usuarios.editarPerfilAjax(my_js_callbackPerfil);" href="#">Editar Perfil</a></div>
          <div class="opcionVer"><a id="cambiarContrasena" onclick="Dajaxice.app_usuarios.cambiarContrasenaAjax(my_js_callbackContrasena);" href="#">Cambiar Contraseña</a></div>
          <div class="opcionVer"><a href="{% url "app_usuarios:logout_view" %}">Cerrar Sesión</a></div>
        </div>
        {% endblock herramientas %}
        {%block dialogs %}
        <div id="formPizarra" style="display:none;"></div>
        <div id="dialogCambiarContrasena" style="display:none;"></div>
        <div id="dialogModificarUsuario" style="display:none;"></div>
        <div id="dialogEditarPerfil" style="display:none;"></div>
        <div id="dialogModificarPizarra" style="display:none;"></div>
        <div id="dialogModificarActividad" style="display:none;"></div>
        <div id="dialogCrearSubactividad" style="display:none;"></div>
        <div id="dialogAsignarActividad" style="display:none;"></div>
        <div id="dialogCrearUsuario"></div>
        {%endblock dialogs%}
        {% block cuerpo %}
        {% endblock cuerpo %}
      </div>	
    </div>
  </body>