app_actividad/urls.py
from django.conf.urls import patterns, url
from app_actividad import views

urlpatterns = patterns('',
	url(r'^crear_actividad/',views.crear_actividad, name='crear_actividad'),
        url(r'^crear_subactividad/',views.crear_subactividad, name='crear_subactividad'), # CREAR SUBACTIVIDAD
        url(r'^crear_actividad/',views.crear_actividad, name='crear_actividad'),
        url(r'^visualizar_subactividad/',views.visualizar_subactividad, name='visualizar_subactividad'),
        url(r'^listar_actividad/',views.listar_actividad, name='listar_actividad'),
        url(r'^modificar_actividad/',views.modificar_actividad, name='modificar_actividad'),
        url(r'^eliminar_actividad/',views.eliminar_actividad, name='eliminar_actividad'),
        url(r'^visualizar_actividad/',views.visualizar_actividad, name='visualizar_actividad'),
        url(r'^modificar_form/',views.generar_form_modificar, name='modificar_form'),
        url(r'^cambiar_estado_actividad/',views.cambiar_estado_actividad, name='cambiar_estado_actividad'),	
        url(r'^form_crear/',views.form_crear, name='form_crear'),
        url(r'^asignar_actividad/',views.asignar_actividad, name='asignar_actividad'),
        url(r'^invitar_usuario/',views.invitar_usuario, name='invitar_usuario')
)

app_comentarios/urls.py
from django.conf.urls import patterns, url
from app_comentarios import views

urlpatterns = patterns('',
  url(r'^crear_comentario/',views.crear_comentario, name='crear_comentario'),
  url(r'^eliminar_comentario/',views.eliminar_comentario, name='eliminar_comentario'),
)

app_log/urls.py
from django.conf.urls import patterns, url

from app_log import views as views_log
from django.contrib.auth import views as views_admin

urlpatterns = patterns('',
    url(r'^consultar_log/', views_log.visualizar_accion_user, name='visualizar_log_user'),
)

app_pizarras/urls.py
from django.conf.urls import patterns, url
from rest_framework.urlpatterns import format_suffix_patterns

from app_pizarras import views
from app_pizarras import rest_views

urlpatterns = patterns('',
        url(r'^crear_pizarra/',views.crear_pizarra, name='crear_pizarra'),
        url(r'^listar_pizarra/',views.listar_pizarra, name='listar_pizarra'),
        url(r'^modificar_pizarra/',views.modificar_pizarra, name='modificar_pizarra'),
        url(r'^modificar_form/',views.generar_form_modificar, name='modificar_form'),
        url(r'^eliminar_pizarra/',views.eliminar_pizarra, name='eliminar_pizarra'),
        url(r'^visualizar_pizarra/',views.visualizar_pizarra, name='visualizar_pizarra'),
        url(r'^orden_cronologico/',views.vista_orden_cronologico, name='orden_cronologico'),
        url(r'^orden_estados/',views.vista_orden_estados, name='orden_estados'),
        url(r'^orden_avance/',views.vista_orden_avance, name='orden_avance'),
        url(r'^listar_pizarras_rest/$', rest_views.PizarraList.as_view(), name='listar_pizarra_rest'),
        url(r'^rest_pizarras_usuario/(?P<username>[\w]+)/$', rest_views.PizarraList.as_view(), name='pizarras_usuarios_rest'),
        url(r'^rest/(?P<pk>[0-9]+)/$', rest_views.PizarraDetail.as_view(), name='rest_pizarra_detail'),
)

urlpatterns = format_suffix_patterns(urlpatterns)

proyecto_pizarras/urls.py
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from dajaxice.core import dajaxice_autodiscover, dajaxice_config

from app_actividad.models import Actividad
from app_usuarios import views as views_usuarios
from app_usuarios.models import UserProfile
from app_usuarios.models import UserProfile
from app_pizarras.models import Pizarra
from app_log.models import Accion
from app_comentarios.models import Comentario

#admin.site.register(UserProfile)
admin.site.register(Pizarra)
admin.site.register(Actividad)
admin.site.register(Comentario)
admin.site.register(Accion)
admin.autodiscover()
dajaxice_autodiscover()

urlpatterns = patterns('',
    url(r'^admin/',                                            include (admin.site.urls)),
    url(r'^account/',                                          include ('django.contrib.auth.urls')),
    url(r'^$', views_usuarios.login_if, name='login_usuario'),
    url(r'^usuarios/',                                         include ('app_usuarios.urls', namespace="app_usuarios")),
    url(r'^pizarras/',                                         include ('app_pizarras.urls', namespace="app_pizarras")),
    url(r'^actividad/',                                        include ('app_actividad.urls', namespace="app_actividad")),
    url(r'^comentarios/',                                      include ('app_comentarios.urls', namespace="app_comentarios")),
    url(dajaxice_config.dajaxice_url,                          include ('dajaxice.urls')),
    url(r'^log/',                                              include ('app_log.urls', namespace="app_log")),
)

urlpatterns += staticfiles_urlpatterns()

app_actividad/forms.py
from django import forms
from django.core.exceptions import ValidationError
from datetime import datetime
import re

"""
Form para crear nueva pizarra
"""
class CrearActividadForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    descripcion = forms.CharField(max_length=100, widget=forms.Textarea)
    fecha_inicio = forms.DateField()
    fecha_final = forms.DateField()

class ModificarActividadForm(forms.Form):
    nombreact = forms.CharField(max_length=50)
    descripcionact = forms.CharField(max_length=100)
    fechainicial = forms.DateField()
    fechaentrega = forms.DateField()
    
class CambiarEstadoForm(forms.Form):
    estadoact = forms.CharField(max_length=15)
    
class AsignarForm(forms.Form):
     correo = forms.EmailField(max_length=50, error_messages={'invalid': ('La direccion de correo es invalida')})

app_actividad/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.template import RequestContext
from django.views.decorators.csrf import csrf_exempt
from django.core.mail import send_mail

from app_usuarios.models import UserProfile
from app_pizarras.forms import CrearPizarraForm
from app_pizarras.models import *
from app_actividad.forms import *
from app_actividad.models import *
from app_comentarios.models import *
from app_log.models import ManejadorAccion, Accion
from app_log.models import ManejadorAccion, Accion

#requiere permisos para agregar actividad
#@permission_required('app_pizarras.add_actividad')
"""
Falta arreglar este metodo para que guarde los datos de los usuraios involucrados
"""
@csrf_exempt
def crear_actividad(request):
  if request.method == 'POST':
    form = CrearActividadForm(request.POST)
    if form.is_valid():
      data = form.cleaned_data

      nombreact = data['nombre']
      descripcionact = data['descripcion']
      fechainicial = data['fecha_inicio']
      fechaentrega = data['fecha_final']

      piz=Pizarra.objects.get(idpiz=request.POST['idpiz'])
      user = request.user
      act = Actividad.objects.get(idpizactividad = piz, actividad_padre = None)
      
      crearActividad(nombreact,descripcionact,fechainicial,fechaentrega,piz,user,act)
      calcularAvance(act.idact)

      lista = obtener_actividades(request.POST['idpiz'])
      lista = obtener_misActividades(request.POST['idpiz'], user)
      #Lista de arboles de mis actividades   
      root = []
      for elem in lista:
        root.append(Node(elem))

      for i in range(0,len(root)):
        root[i].generate_tree()
        string = '{'
        string += root[i].generate_json()
        string += '}'
        print string

      colab = colaboradores(request.POST['idpiz'])
      usuario = request.user
      orden = orden_cronologico(piz.idpiz, usuario)
      ordenE = orden_por_estados(piz.idpiz, usuario)
      return render(request,'app_pizarras/vistaPizarra.html',{ 'pizarra' : piz, 'colaboradores': colab, 'lista': lista, 'orden': orden, 'ordenE': ordenE, 'colaboradores': colab, 'arbol': string, })

    else:
      return render(request,'app_actividad/crear_actividad.html',{'form':form, 'idpiz':request.POST['idpiz']})
  
@csrf_exempt
def crear_subactividad(request):
  if request.method == 'POST':
    form = CrearActividadForm(request.POST)
    if form.is_valid():
      print "validoooooooooo "
      data = form.cleaned_data

      nombreact = data['nombre'] # NOMBRE DE LA ACTIVIDAD
      descripcionact = data['descripcion'] # DESCRIPCION DE LA ACTIVIDAD
      fechainicial = data['fecha_inicio'] # FECHA INICIAL
      fechaentrega = data['fecha_final'] # FECHA DE ENTREGA
      
      idpizactividad = request.POST['idpiz']
      pizarra = Pizarra.objects.get(idpiz=idpizactividad)
      padre = Actividad.objects.get(idact=request.POST['idact']) # IDACT.. ES OBTENER EL ID DE LA ACTIVIDAD.
      user = request.user
      
      crearActividad(nombreact,descripcionact,fechainicial,fechaentrega,pizarra,user,padre)
      calcularAvance(padre.idact)

      return visualizar_actividad(request)
    else:
      print "invalidooooooooooooooo!"

      return render(request,'app_actividad/crear_subactividad.html',{'form': form, 'idact':request.POST['idact'],'idpiz':request.POST['idpiz']})

  
def form_crear(request):
    """
    Metodo que genera el form crear
    """
    if request.method == 'POST':
        idpiz = request.POST['idpiz']
        form = CrearActividadForm()	
        return render(request, 'app_actividad/crear_actividad.html', { 'idpiz' : idpiz, 'form' : form })

    lista = obtener_actividades(request)
    return render(request, 'app_actividad/listar.html', { 'lista' : lista, })
	    
def listar_actividad(request):
    lista = obtener_actividades(request)
    return render(request, 'app_actividad/listar.html', { 'lista' : lista, })		
      
def eliminar_actividad(request):

    if request.method == 'POST':
        idact = request.POST['idact']
        idpiz = request.POST['idpiz']
        piz = Pizarra.objects.get(idpiz = idpiz)
        act = Actividad.objects.get(idact = idact)    
        usuario = request.user

        
        eliminarActividad(idact, usuario)
        if act.actividad_padre != None:
          calcularAvance(act.actividad_padre.idact)

        colab = colaboradores(idpiz)
        #Lista de mis actividades
        lista = obtener_misActividades(request.POST['idpiz'], usuario)
        #Lista de arboles de mis actividades   
        string = ''
        root = []
        for elem in lista:
            root.append(Node(elem))
        
        for i in range(0,len(root)):
            root[i].generate_tree()
            string = '{'
            string += root[i].generate_json()
            string += '}'
            print string
                
        #Listas de ordenes a mostrar en la pagina
        orden = orden_cronologico(idpiz, usuario)
        ordenE = orden_por_estados(idpiz, usuario)
        return render(request,'app_pizarras/vistaPizarra.html',{ 'pizarra' : piz, 'colaboradores': colab, 'lista': lista, 'orden': orden, 'ordenE': ordenE, 'arbol': str(string), })
    

    #no se que retornar si no es post asi que retorno la vista anterior y ya
    return listar_pizarra(request)
        
@csrf_exempt        
def visualizar_actividad(request):
    if request.method== 'POST':
        idact = request.POST['idact']
        act = Actividad.objects.get(idact=idact)
        piz = act.idpizactividad
        lista = obtener_comentarios(idact)
        listasub = obtener_subactividades(idact)
        actEsHoja = esHoja(idact)
        return render(request,'app_actividad/vistaActividad.html',{ 'actividad' : act, 'lista': lista, 'listasub':listasub, 'pizarra':piz, 'actEsHoja':actEsHoja, })

    lista = obtener_actividades(request)
    return render(request, 'app_actividad/vistaActividad.html', { 'lista' : lista, })
    
    
# SUBACTIVIDADES    

def listar_subactividad(request):
    lista = obtener_subactividades(request)
    return render(request, 'app_actividad/listar.html', { 'lista' : lista, })	    
    
@csrf_exempt        
def visualizar_subactividad(request):
    if request.method== 'POST':
        idact = request.POST['idact']
        act = Actividad.objects.get(idact=idact)
        lista = obtener_subactividad(idact)
        return render(request,'app_actividad/vistaActividad.html',{ 'actividad' : act, 'lista': lista})

    lista = obtener_subactividades(request)
    return render(request, 'app_actividad/vistaActividad.html', { 'lista' : lista, })
    
@csrf_exempt
@login_required
def modificar_actividad(request):
  """
  Metodo que sirve para modificar una pizarra de la base de datos
  """
  if request.method == 'POST':
    if request.POST.__contains__('idact'):
      form = ModificarActividadForm(request.POST)
      if form.is_valid():
      	data = form.cleaned_data
      	#Variables que se pasaran al metodo CreadorPizarra
      	for elem in data:
      	  print elem

      	idact = request.POST['idact']
      	nombreact = data['nombreact']
      	descripcionact = data['descripcionact']
      	fechaInicial = data['fechainicial']
      	fechaEntrega = data['fechaentrega']
      	act = Actividad.objects.get(idact = idact)
      	user = request.user
        modificarActividad(idact,nombreact,descripcionact,fechaInicial,fechaEntrega, user)
        act = Actividad.objects.get(idact = idact)
        lista = obtener_comentarios(idact)
        return visualizar_actividad(request)
      
      else:
      	print "form no valido"
      	idact = request.POST['idact']
      	lista = []
      	lista.append(request.POST['nombreact'])
      	lista.append(request.POST['descripcionact'])
      	lista.append(request.POST['fechainicial'])
      	lista.append(request.POST['fechaentrega'])
	return visualizar_actividad(request)
	
@csrf_exempt	
@login_required
def cambiar_estado_actividad(request):
  if request.method == 'POST':
        idact = request.POST['idact']
        estado = request.POST['estadoact']
        print "holaaaaaaaaaa soy idact",
        print idact
        if estado != "null":
            cambiarEstado(idact,estado, request.user)
        lista = obtener_comentarios(idact)
        act = Actividad.objects.get(idact = idact)
        return visualizar_actividad(request)

@csrf_exempt
@login_required
def generar_form_modificar(request):
    """
    Metodo que genera el form de modificar
    """
    if request.method == 'POST':
        idact = request.POST['idact']
        lista = []
        lista.append(request.POST['nombreact'])
        lista.append(request.POST['descripcionact'])
        lista.append(request.POST['fechainicial'])
        lista.append(request.POST['fechaentrega'])
        return render(request, 'app_actividad/modificar_actividad.html', { 'idact' : idact, 'lista' : lista })

    lista = obtener_actividades(request)
    return render(request, 'app_actividad/listar.html', { 'lista' : lista, })
    
def asignar_actividad(request):
    
    return render(request,'app_actividad/asignar_actividad.html',{'idact':request.POST['idact'], 'idpiz':request.POST['idpiz']})

@csrf_exempt
def invitar_usuario(request):
    ##
    #Metodo que asigna una actividad a un derminado usuario
    #@author German Leon
    #@date 29-11-2012
    #@version 1.0
    #@param request
    
    if request.method == 'POST':
        id_actividad = request.POST['id_actividad']
        recipiente = request.POST['recipiente']
        id_pizarra = request.POST['idpiz']
        
        act = Actividad.objects.get(idact=id_actividad)
        piz = Pizarra.objects.get(idpiz=id_pizarra)
        nombre_pizarra = piz.nombrepiz
        print nombre_pizarra
        nombre_actividad = act.nombreact
        
        if not User.objects.filter(email=recipiente).exists():

templates/app_actividad/crear_subactividad.html
<script>
  calendarios();
</script>
  <form action="{% url "app_actividad:crear_subactividad" %}" id="formCrearSubactividad" method="post" >
  {% csrf_token %}
    <fieldset id="body">
      <fieldset>
	  <label for="nombreact"> Nombre</label>
	  <input type="text" name="nombre" id="id_nombre" />
      </fieldset>
      <fieldset>
	  <label for="descripcionact">Descripcion</label>
	  <textarea type="text" name="descripcion" rows="5" id="id_descripcion"></textarea>
      </fieldset>
      <fieldset>
	  <label for="fechainicial">Fecha Inicio</label>
	  <input type="text" name="fecha_inicio" id="id_fecha_inicio"/>
      </fieldset>
      <fieldset>
	  <label for="fechaentrega">Fecha Entrega</label>
	  <input type="text" name="fecha_final" id="id_fecha_final" />
      </fieldset>
      <input id="idact" name="idact" type="hidden" value="{{idact}}"/>
      <input id="idpiz" name="idpiz" type="hidden" value="{{idpiz}}"/>
    </fieldset>
  </form>

templates/app_actividad/infoActividad.html
{% extends "app_usuarios/template.html" %}
{% load staticfiles %}
{% block titulo %}Actividad "{{actividad.nombreact}}"{% endblock titulo %}
{% block css %}
<link href="{% static "css/vistaPizarra_style.css" %}" rel="stylesheet" type="text/css"/>
{% endblock css %}

{% block botones %}
<a id="crearActividad" onclick="Dajaxice.app_actividad.crearActividadForm(my_js_callbackActividad, {'data': {{pizarra.idpiz}}});" class="opcionesDer" href="#">Crear Actividad</a>
{% endblock botones %}
{% block cuerpo %}

<div id="columna">
  <table>
    <tr>
      <td>
        <h>Nombre</h></br>
        {{actividad.nombreact}}
      </td>
    </tr>
    <tr>
      <td>
        <h>Creador</h></br>
        {{actividad.logincreador}}
      </td>
    </tr>
    <tr>
      <td>
        <h>Descripcion</h></br>
        {{actividad.descripcionact}}
      </td>
    </tr>
    <tr>
      <td>
        <h>Fecha inicial</h></br>
        {{actividad.fechainicial}}
      </td>
    </tr>
    <tr>
      <td>
        <h>Fecha de entrega</h></br>
        {{actividad.fechaentrega}}
      </td>
    </tr>
    <tr>
      <td>
        <!-- modificar actividad -->
        <form action="{% url "app_actividad:modificar_form" %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="idact" value="{{actividad.idact}}"/>
          <input type="hidden" name="nombreact" value="{{actividad.nombreact}}"/>
          <input type="hidden" name="descripcionact" value="{{actividad.descripcionact}}"/>
          <input type="hidden" name="fechainicial" value="{{actividad.fechainicial}}"/>
          <input type="hidden" name="fechaentrega" value="{{actividad.fechaentrega}}"/>
          <input type="submit" value="Modificar" />
        </form>
      </td>
    </tr>
    <tr>
      <td>
        <!-- cambiar estado -->
        <form name="CambiarEstadoForm" action="{% url "app_actividad:cambiar_estado_actividad" %}" method="post"> 
          {% csrf_token %}
          <select name="estadoact">
            <option value="null"> Estado </option>
            <option value="s"> Sin Asignar </option>
            <option value="c"> Completada </option>
            <option value="r"> Retrasada </option>
            <option value="e"> En Ejecucion </option>
            <option value="p"> Postergada </option>
          </select> 
          <input type="hidden" name="idact" value="{{actividad.idact}}"/>
          <input type="submit" value="Cambiar Estado" />
        </form>
      </td>
    </tr>
  </table>
</div>
<div id="comentarios">
  <!-- hacer comentarios -->
  <form action="{% url "app_comentarios:crear_comentario" %}" id="crear_comentario" method="post">{% csrf_token %}
    <input type="hidden" name="idact" value="{{actividad.idact}}"/>
    <textarea id="contenido" name="contenido"></textarea>
    <input type="submit" value="Comentar"/>
  </form>
</div>
{% endblock cuerpo%} 

templates/app_actividad/modificar_actividad.html
<script>
  calendarios();
</script>

<form action="{% url "app_actividad:modificar_actividad" %}" id="modificarActividadForm" method="post" onsubmit="if(!confirm('Seguro desea modificar esta actividad?')) return false">
  {% csrf_token %}
  <fieldset id="body">
    <input type="hidden" name="idact" value="{{idact}}" />
    <fieldset>
      <label for="nombreact"> Nombre Actividad</label>
      <input type="text" name="nombreact" id="id_nombre" value="{{lista.0}}"/>
    </fieldset>
    <fieldset>
      <label for="descripcion">Descripción Actividad</label>
      <textarea class="input-large" rows= "5" type="text" name="descripcionact" id="id_descripcion">{{lista.1}} </textarea>
    </fieldset>
    <fieldset>
      <label for="fechainicial">Fecha de Inicial</label>
      <input type="text" name="fechainicial" id="id_fecha_inicio" value="{{ lista.2 }}"/>
    </fieldset>
    <fieldset>
      <label for="fechaentrega">Fecha de Entrega</label>
      <input type="text" name="fechaentrega" id="id_fecha_final" value="{{ lista.3 }}"/>
    </fieldset>
  </fieldset>
</form>

templates/app_actividad/vistaActividad.html
{% extends "app_usuarios/template.html" %}
{% load staticfiles %}
{% block titulo %}Actividad "{{actividad.nombreact}}"{% endblock titulo %}
{% block css %}
<link href="{% static "css/vistaActividad_style.css" %}" rel="stylesheet" type="text/css"/>
{% endblock css %}
{% block javascript %}
<script>
$(document).ready(function(){
  dialog();
  barraUsuario();
});
$(function(){
  $( "#arbol" ).tabs();
})
</script>
{% endblock javascript %}

{% block botones %}
<form action="{% url "app_pizarras:visualizar_pizarra"%}" style="margin: 0;" method="post">
  {%csrf_token%}
  <input type="hidden" name="idpiz" value="{{actividad.idpizactividad.idpiz}}"/>
  <input type="image" class="opcionesIzq" src="{% static "img/back.png" %}" style="height: 20px;">
</form>

<form action="{% url "app_actividad:eliminar_actividad" %}" onsubmit="if(!confirm('Seguro desea eliminar esta actividad?')) return false"  style="margin: 0;" method="post">
  {%csrf_token%}
  <input type="hidden" name="idact" value="{{actividad.idact}}"/>
  <input type="hidden" name="idpiz" value="{{pizarra.idpiz}}"/>
  <input type="image" class="opcionesIzq" src="{% static "img/rem.png" %}" style="height: 20px;"/>
</form>

<a class="opcionesIzq" style="height: 40px; width: 40px; padding: 0">
  <form action="{% url "app_actividad:modificar_form" %}" onsubmit="return false;" method="post" style="margin: 0;">
    {% csrf_token %}
    <button type="submit" id="modificarActividad" onclick="Dajaxice.app_actividad.modificarActividadAjax(my_js_callbackModificarActividad, {'idact' : {{actividad.idact}}});"><img style="height: 20px; width: 20px; margin: 8px 3px" src="{% static "img/pencil.png" %}"></button>
  </form>
</a>

<a class="opcionesDer">
<form action="{% url "app_actividad:crear_subactividad" %}" method="post" onclick="return false;">
     {% csrf_token %}
    <button type="submit" id="crearSubactividad" onclick="Dajaxice.app_actividad.crearSubactividadAjax(my_js_callbackCrearSubactividad, {'idact' : {{actividad.idact}}, 'idpiz': {{pizarra.idpiz}}});">Crear subactividad</button>
</form>
</a>

<a class="opcionesDer">
<form action="{% url "app_actividad:asignar_actividad" %}" onclick="return false;" method="post">
  {% csrf_token %}
  <input type="hidden" name="idact" value="{{actividad.idact}}"/>
  <input type="hidden" name="idpiz" value="{{actividad.idpizactividad.idpiz}}"/>
  <button type="submit" id="asignarActividad" onclick="Dajaxice.app_actividad.asignarActividadAjax(my_js_callbackAsignarActividad, {'id_actividad' : {{actividad.idact}}, 'idpiz': {{actividad.idpizactividad.idpiz}}});">Asignar</button>
</form>
</a>
{% endblock botones %}
{% block cuerpo %}

<div id="columna">
  <table>
    <tr>
      <td>
        <h>Nombre</h></br>
		{{data}}
        {{actividad.nombreact}}
      </td>
    </tr>
    <tr>
      <td>
        <h>Creador</h></br>
        {{actividad.logincreador}}
      </td>
    </tr>
    <tr>
      <td>
        <h>Descripción</h></br>
        {{actividad.descripcionact}}
      </td>
    </tr>
    <tr>
      <td>
        <h>Fecha inicial</h></br>
        {{actividad.fechainicial}}
      </td>
    </tr>
    <tr>
      <td>
        <h>Fecha de entrega</h></br>
        {{actividad.fechaentrega}}
      </td>
    </tr>
    <tr>
      <td>
        <h>Estado</h></br>
    		{%if actividad.estadoact == "c"%}
    			Completada
    		{%elif actividad.estadoact == "r"%}
    			Retrasada
    		{%elif actividad.estadoact == "e"%}
    			En Ejecución
    		{%elif actividad.estadoact == "p"%}
    			Postergada
    		{%elif actividad.estadoact == "s"%}
    			Sin Asignar
    		{%endif%}
      </td>
    </tr>
    <tr>
      <td>
        <h>Avance</h></br>
        {{actividad.avanceact}} %
      </td>
    </tr>
    <tr>
      <td>
        <!-- cambiar estado -->
        <form name="CambiarEstadoForm" action="{% url "app_actividad:cambiar_estado_actividad" %}" method="post"> 
          {% csrf_token %}
          <select name="estadoact">
            <option value="null"> Estado </option>
            <option value="s"> Sin Asignar </option>
            {% if actEsHoja %}
            <option value="c"> Completada </option>
            {% endif %}
            <option value="r"> Retrasada </option>
            <option value="e"> En Ejecucion </option>
            <option value="p"> Postergada </option>
          </select>
          <input type="hidden" name="idact" value="{{actividad.idact}}"/>
          <input type="submit" value="OK" />
        </form>
      </td>
    </tr>
  </table>
</div>
<div id="arbol">
  <div id="bordeComents">
    <div id="comentarios">
      <table id="tablaComentarios">
        {% for elem in lista %}
        <tr>
          <td>
           <form action="{% url "app_comentarios:eliminar_comentario" %}" method="post">
             {% csrf_token %}
             <input type="image" src="{% static "img/rem.png" %}" style="height: 10px; float: right;"/>
             {{elem.contenido}}
             <br>
             {{elem.fechacomentario}} {{elem.horacomentario}}
             <br>
             Autor: {{elem.loginusuario}}
             <input type="hidden" name="idcomentario" value="{{elem.idcomentario}}"/>
           </form>
         </td>
       </tr>
       {% endfor %}
     </table>
   </div>
   <!-- hacer comentarios -->
    <div id="comentar">
      <form action="{% url "app_comentarios:crear_comentario" %}" id="crear_comentario" method="post">{% csrf_token %}
        <input type="hidden" name="idact" value="{{actividad.idact}}"/>
        <textarea id="contenido" style="resize: none; width: 200px" name="contenido"></textarea>
        <input type="submit" value="Comentar"/>
      </form>
    </div>
  </div>
  <div id="subactividades">
    {% for elem in listasub %}
      <form action="{% url "app_actividad:visualizar_actividad" %}" style=" display: inline-block;" id="visualizar_actividad" method="post">
        {% csrf_token %}
        <input type="hidden" name="idact" value="{{elem.idact}}" />
          <button class="subact" type="submit"
          style=" {% if elem.estadoact == "c" %}
                    background: #19AC19;
                  {% elif elem.estadoact == "r" %}
                    background: #FFCC00;
                  {% elif elem.estadoact == "p" %}
                    background: #FF0000;
                  {% elif elem.estadoact == "e" %}
                    background: #3399FF;
                  {% elif elem.estadoact == "s"
                    background: #FFFFFF;
                  {% endif %}">
            {{elem.nombreact}}<br>
            {{elem.loginasignado}}<br>
            {{elem.avanceact}} %
          </button>
      </form>
    {% endfor %}
  </div>
</div>
{% endblock cuerpo%} 